# This compose file can be used in development to run both the database and app
# within Docker.

version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.server
        ports:
            - "22300:22300"
        environment:
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=joplin
            - POSTGRES_DATABASE=joplin
            - POSTGRES_USER=joplin
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
            - APP_BASE_URL=http://localhost:22300
            - APP_PORT=22300
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=joplin
            - POSTGRES_USER=joplin
            - POSTGRES_DB=joplin
