version: "3"

x-uffizzi:
  ingress:
    service: novnc
    port: 80

services:

  novnc:
    container_name: vnc
    image: dorowu/ubuntu-desktop-lxde-vnc
    environment:
      - VNC_VIEW_ONLY=true
    ports:
      - "80:80"
    restart: on-failure
    privileged: true
    entrypoint: /bin/sh
    command:
         - "-c"
         - "sudo apt-get update -y && apt-get install libfuse2 -y && cd /tmp ; apt-get download fuse && cd /tmp ; dpkg-deb -x fuse_* . && cd /tmp ; dpkg-deb -e fuse_* && cd /tmp ; rm fuse_*.deb && cd /tmp ; echo -en '#!/bin/bash\nexit 0\n' > DEBIAN/postinst && cd /tmp ; dpkg-deb -b . /fuse.deb && cd /tmp ; dpkg -i /fuse.deb"
    cap_add:
      - SYS_ADMIN
    deploy:
      resources:
        limits:
          memory: 4000M
